### ISSUE TITLE
Gathering the results from analysis

### ISSUE THREAD

**Issue by psanchez1982** [smartinsightsfromdata/rpivotTable#29] opened 2015-08-07 13:53 UTC
Is there a way to save the results from analysis over the pivot table to a Data Frame? It would be very useful. Today the analysts create a lot of SQL queries or use Excel, with your Pivot Table they can use it and write it on a SQL Table or export to an Excel spreadsheet.

**Comment by smartinsightsfromdata** [comment] 2015-08-27 14:00
@psanchez1982 I am not very clear on your point(s).

- The enhancement relative to the ability to store some of the analysis is documented in #12 (and in this respect this is a duplicate of #12 .  I haven't got much time so far to work on this but it is on my plan.

- On the other hand this tool is not designed to save to Excel or anything similar. If you have similar needs perhaps you should consider using rhandsontable which has recently introduced this feature.

I hope it helps.

**Closed by smartinsightsfromdata** 2015-08-27 14:00 UTC

**Comment by psanchez1982** [comment] 2015-08-31 19:23
Well. It could be very useful. You have a very powerful tools that can
compete with SAS.

Regards,

Patricio Sanchez Alvial
Ingeniero Civil Informático
Cel: 78774916

**Comment by smartinsightsfromdata** [comment] 2015-10-26 21:18
@psanchez1982 The feature you requested is now experimentally available.  See issue #12 at the very end of the thread.
[There is a comment in stackoverflow also](http://stackoverflow.com/questions/33214397/download-rpivottable-ouput-in-shiny/33352302#33352302)
