### ISSUE TITLE
rpivotTable- hiddenFromAggregators and hiddenFromDragDrop options are not working

### ISSUE THREAD

**Issue by sadaftariq** [smartinsightsfromdata/rpivotTable#79] opened 2017-10-12 15:43 UTC
I tried to find any example related to this topic but didn't find any clear answer. Issue related to this was asked and closed. Due to my limited knowledge in R shiny, I couldn't get a solution to my problem. 

Firstly, I'm trying to hide a specific variable from drag and drop panels while constructing a pivot table. Secondly, I want to use a specific variable as an aggregator and remove all rest of the variables from the aggregator list.

Note: I don't want to remove that variable from the data frame. Options for example rows, cols, vals, aggregatorName, rendererName are working perfectly. But hiddenFromDragDrop and hiddenFromAggregators are not working, or I'm using them in wrong way.

My data is too big. An example code to clear my question is given here. This data has 4 variables, Eye, Sex, Hair, and Freq. I want to hide "Freq" from the DragDrop list and "Eye","Hair","Sex" from aggregator attribute list. I'm looking for a working example. I'll appreciate your help. Thanks

library(rpivotTable)
data(HairEyeColor)
rpivotTable(data = HairEyeColor, rows = "Hair",cols="Eye", vals = "Freq", 
aggregatorName = "Sum", rendererName = "Table", 
hiddenFromDragDrop="Freq",hiddenFromAggregators=c("Eye","Hair","Sex"), width="100%", height="400px")
-- | --
-- | --

-- | --

**Comment by nicolaskruchten** [comment] 2017-10-13 13:57
The issue is most likely because the `hiddenFromDragDrop` and `hiddenFromAggregators` options are in PivotTable.js version 2.15.0 and rpivotTable only contains 2.11.0. Once @smartinsightsfromdata updates it it should work :)

**Comment by nicolaskruchten** [comment] 2018-01-30 20:40
This should be fixed in version 0.3.0 of this library! https://github.com/smartinsightsfromdata/rpivotTable/releases/tag/v0.3.0

**Closed by nicolaskruchten** 2018-01-30 20:40 UTC
