### ISSUE TITLE
Rstudio hang after using sqldf package with rpivottable

### ISSUE THREAD

**Issue by maciejorlos** [smartinsightsfromdata/rpivotTable#28] opened 2015-07-28 08:42 UTC
I am working on ubuntu 14.04 and  after putting such code:

    require(sqldf)
    require(rpivotTable)
    data(mtcars)
    rpivotTable(mtcars)
My rstudio hangs

**Comment by smartinsightsfromdata** [comment] 2015-08-10 11:29
@maciejorlos it works for me on my OS X yosemite laptop.

I'm using ```RStudio```  0.99.467
Could you kindly post your ```sessionInfo()```?

Thanks

**Comment by smartinsightsfromdata** [comment] 2015-08-21 08:21
@maciejorlos see #30: older versions of RStudio may cause problems.

**Comment by smartinsightsfromdata** [comment] 2015-08-27 14:01
I'm closing it for now: I need proper sessionInfo() and a reproducible example.

**Closed by smartinsightsfromdata** 2015-08-27 14:01 UTC
