### ISSUE TITLE
pandoc error 67 when using rmarkdown with rpivottable

### ISSUE THREAD

**Issue by alexdeng** [smartinsightsfromdata/rpivotTable#34] opened 2015-10-15 16:55 UTC
Got this error: 

/home/expat/R/x86_64-pc-linux-gnu-library/3.2/rpivotTable/htmlwidgets/lib/jqueryui/images/animated-overlay.gif: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67

it looks like the whole image folder is not there and pandoc somehow needs it

pandoc commandline (used knit HTML from rstudio)
/usr/bin/pandoc +RTS -K512m -RTS pivottable.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output pivottable.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /usr/local/lib/R/site-library/rmarkdown/rmd/h/default.html --variable 'theme:bootstrap' --include-in-header /tmp/RtmpNYrrbC/rmarkdown-strb2e44afa1939.html --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --no-highlight --variable highlightjs=/usr/local/lib/R/site-library/rmarkdown/rmd/h/highlight

**Comment by smartinsightsfromdata** [comment] 2015-10-15 18:48
@alexdeng Could I have a reproducible example please?

**Comment by smartinsightsfromdata** [comment] 2015-10-15 18:52
Just found this issue - perhaps related?
https://github.com/rstudio/rmarkdown/issues/419

**Comment by smartinsightsfromdata** [comment] 2015-10-23 12:55
close - ready to re-open as soon as I get a reproducible example

**Comment by smartinsightsfromdata** [comment] 2015-10-23 20:18
@alexdeng  I've just fixed this problem in the dev branch.  Please look for the next release.

**Comment by smartinsightsfromdata** [comment] 2015-10-23 21:51
@alexdeng Please check on the dev branch.  I cannot merge at the moment as I still have a conflict with shiny date picker (due to a jquery-ui conflict)

**Comment by alexdeng** [comment] 2015-10-24 06:38
Thanks @smartinsightsfromdata ! I'll let you know once I tried it. Looks from the commit the missing files are added so I guess it will be resolved.

**Comment by smartinsightsfromdata** [comment] 2015-10-24 10:11
@alexdeng I committed to master the relative changes. Thanks for your report!

**Closed by smartinsightsfromdata** 2015-10-24 10:11 UTC
